export type JSONValue = string | number | boolean | JSONObject | JSONArray | null;

export type JSONObject = {
  readonly [x in string]: JSONValue;
};

type JSONArray = readonly JSONValue[];

export const TransactionEventTypeList = [
  "AUTHORIZATION_ACTION_REQUIRED",
  "AUTHORIZATION_ADJUSTMENT",
  "AUTHORIZATION_FAILURE",
  "AUTHORIZATION_REQUEST",
  "AUTHORIZATION_SUCCESS",
  "CANCEL_FAILURE",
  "CANCEL_REQUEST",
  "CANCEL_SUCCESS",
  "CHARGE_ACTION_REQUIRED",
  "CHARGE_BACK",
  "CHARGE_FAILURE",
  "CHARGE_REQUEST",
  "CHARGE_SUCCESS",
  "INFO",
  "REFUND_FAILURE",
  "REFUND_OR_CANCEL_FAILURE",
  "REFUND_OR_CANCEL_REQUEST",
  "REFUND_OR_CANCEL_SUCCESS",
  "REFUND_REQUEST",
  "REFUND_REVERSE",
  "REFUND_SUCCESS",
];
